"""Add design_config to CartItem and OrderItem

Revision ID: 5b8668d53929
Revises: 675d65b17391
Create Date: 2024-11-24 23:54:20.593176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8668d53929'
down_revision = '675d65b17391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('design_config', sa.JSON(), nullable=True, comment='{position, scale, rotation}'))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('design_config', sa.JSON(), nullable=True, comment='{position, scale, rotation}'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('design_config')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('design_config')

    # ### end Alembic commands ###
