"""Add default shipping info to User model

Revision ID: 675d65b17391
Revises: b98c81b03a5d
Create Date: 2024-11-24 01:45:07.360356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '675d65b17391'
down_revision = 'b98c81b03a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('shipping_address',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='{name, address, city, postal_code, country}',
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_shipping_info', sa.JSON(), nullable=True, comment='{name, address, city, postal_code, country}'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_shipping_info')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('shipping_address',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='{name, address, city, postal_code, country}',
               existing_nullable=False)

    # ### end Alembic commands ###
